# Time-stamp: <2023-08-09 16:51:45>
[project]
name = "vcf2py"
version = "0.1.1"
authors = [
  { name="mikpom", email="mikpom@mikpom.ru" },
]
description = "Tools to process genomic variant data with Numerical Python"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pysam"
]
[project.urls]
"Homepage" = "https://github.com/mikpom/vcf2py"

